In [1]:
#Propacacion hacia delante
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#defined sigmoid
def sigmoid(z):
    s = 1.0 / (1.0 + np.exp(-1.0 * z))
    return s
#derivitate of sigmoid
def sigmoid_derivative(z):
    ans = sigmoid(z) * (1 - sigmoid(z))
    return ans
# AW + b
def z(inputs, weights, onesOne, onesTwo):
    #adds a vector(bia) to our inputs
    inputs = np.vstack((inputs, onesOne))
    #adds a vector (bias) to our weights
    weights = np.hstack((weights, onesTwo))
    #Z y es obtained
    z = np.dot(weights, inputs)
    return z

In [3]:
#a0 of our Neurol Netowrk
inputs = np.array([
    [4.7, 6.0],
    [6.1, 3.9],
    [2.9, 4.2],
    [7.0, 5.5]
])
#Our target matrix
targets = np.array([
    [3.52, 4.02],
    [5.43, 6.23],
    [4.95, 5.76],
    [4.70, 4.28]
])

In [4]:
#Randomly Generatoed matrix 3x2
w10 = np.random.uniform(low=0.0, high=1.0, size=(3, 2))
#Randomly Generatoed matrix of 2x3
w21 = np.random.uniform(low=0.0, high=1.0, size=(2, 3))
#Declaration of ones that are going to be appended to the matrixes
print(w21)

[[ 0.96138092  0.51236509  0.4850129 ]
 [ 0.1468871   0.88928305  0.85812612]]


In [5]:
#Declaration of ones that are going to be appended to the matrixes
fourOnes = np.ones((1, 4))
threeOnes = np.ones((3, 1))
twoOnes = np.ones((2,1))

In [6]:
#transposing inputs to be able to append vector of ojnes
inputs = np.transpose(inputs)
#callin z funciton to get our z one
z1 = z(inputs, w10, fourOnes, threeOnes)

In [7]:
#se optiene a1 ingresando la z a la funciona de activacion
a1 = sigmoid(z1)
#se obtiene z2
z2 = z(a1, w21, fourOnes, twoOnes)

In [8]:
#se optiene a2 ingresando la z2 a la funciona de activacion d
a2 = sigmoid(z2)

In [9]:
targets = np.transpose(targets)
#Using the subtract function from numpy we subtract the matrix
error = np.subtract(targets, a2)
print("Error", error)


Error [[ 2.57306878  4.4830828   4.00422119  3.75242984]
 [ 3.07949623  5.2895291   4.82165207  3.33827088]]


In [10]:
#obtaine de loss of the function
loss = np.power(error, 2)
print('Loss', loss)


Loss [[  6.62068295  20.09803139  16.03378731  14.08072969]
 [  9.48329702  27.97911814  23.24832871  11.14405247]]


In [11]:
#define derivate function for sigmoid
f1 = sigmoid_derivative(z2)
#A1 is added a vertically an array of four ones
a1Aum = np.vstack((a1, fourOnes))

In [12]:
#define delta K and multiply the error with de derivative function
deltaK = np.multiply(error, f1)
#we finish the equation by using dot function to multiply the current 
#delta K with a1Aum
deltaK = 2 * np.dot(deltaK, a1Aum)
#print delta K
print(deltaK)

[[ 1.42504046  1.4249329   1.40579151  1.43627342]
 [ 1.77205908  1.77177249  1.74664676  1.78680771]]


In [13]:
#Define variables needed for delta J
f2 = sigmoid_derivative(z1)
#Added ones vertically to inputs
inputsAum = np.vstack((inputs, fourOnes))
print(inputsAum)

[[ 4.7  6.1  2.9  7. ]
 [ 6.   3.9  4.2  5.5]
 [ 1.   1.   1.   1. ]]


In [14]:
deltaJ = np.dot(w21.T, deltaK)
deltaJ = np.multiply(deltaJ, f2)
deltaJ = np.dot(deltaJ, inputsAum.T)
print(deltaJ)


[[  6.46079699e-03   8.61827017e-03   2.01666596e-03]
 [  5.84668913e+00   5.67815561e+00   1.16875772e+00]
 [  2.21613088e-01   1.94296521e-01   4.48924074e-02]]
